API_HOST_URL: 'https://etraining.moe.gov.sa'
ENVIRONMENT_DISPLAY_NAME: 'etraining.moe.gov.sa'
PLATFORM_NAME: 'MOE'
PLATFORM_DESTINATION_NAME: 'etraining.moe.gov.sa'
FEEDBACK_EMAIL_ADDRESS: 'support@ilearn.ws'
DEBUG: true
OAUTH_CLIENT_ID: '5ec60b6c97312333ce77'
OAUTH_CLIENT_SECRET: '8cd9eb6ec4a9bc9e536f7f66379b7a0c245285e8'

MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true

COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }

#OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true

DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
