API_HOST_URL: 'https://edxmoe.ilearnme.com'
ENVIRONMENT_DISPLAY_NAME: 'edxmoe.ilearnme.com'
PLATFORM_NAME: 'MOE'
PLATFORM_DESTINATION_NAME: 'edxmoe.ilearnme.com'
FEEDBACK_EMAIL_ADDRESS: 'support@ilearn.ws'
DEBUG: true
OAUTH_CLIENT_ID: '0d7d01a1f2a866866285'
OAUTH_CLIENT_SECRET: 'be3a30b12ca7f198431ae670c7160beef0c2466f'

MY_VIDEOS_ENABLED: true
COURSE_VIDEOS_ENABLED: true

COURSE_ENROLLMENT : { TYPE : 'native', SEARCH_BAR_ENABLED : true }

OAUTH_ENFORCE_SECURE: true
PUSH_NOTIFICATIONS: true
USER_PROFILES_ENABLED: true

DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
